# Generated by Django 2.2.13 on 2020-08-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubanshort',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
    ]
